version : '3'

services:
  apt-cacher-ng:
    image: "lramm/apt-cacher-ng"
    restart: unless-stopped
    ports:
      - 3142:3142
    volumes:
      - ./cache:/var/cache/apt-cacher-ng/
      - ./mirror_list:/etc/apt-cacher-ng/mirror_list.d/
